
services:

  archivosprivados:
    build:
      context: .
      dockerfile: Dockerfile
    image: archivosprivados:0.0.1
    container_name: archivosprivados
    volumes:
      - .:/srv/cf.archivosprivados/
      - /srv/cf.archivosprivados/node_modules
      - ../cf.archivospublicos/frontend/assets/:/srv/cf.archivosprivados/frontend/assets/archivospublicos
    environment:
       NODE_ENV: "production"
       PORT: ${PORT:-2203}
    ports:
      - "127.0.0.1:2203:2203"
