
services:

  archivosprivados:
    build:
      context: .
      dockerfile: Dockerfile
    image: archivosprivados:0.0.1
    container_name: archivosprivados
    env_file:
      - .env.production
    volumes:
      - ../cf.archivospublicos/frontend/assets/domains/archivospublicos.jotace.cl/:/srv/cf.archivosprivados/frontend/assets/domains/archivosprivados.jotace.cl/archivospublicos
    environment:
       NODE_ENV: "production"
       PORT: ${PORT:-2203}
    ports:
      - "127.0.0.1:2203:2203"
