version: "3.10"

services:

  archivosprivados:
    build:
      context: .
      dockerfile: Dockerfile
    image: archivosprivados:0.0.1
    container_name: archivosprivados
    volumes:
      - .:/srv/cf.archivosprivados/
      - /srv/cf.archivosprivados/node_modules
    environment:
       NODE_ENV: "production"
       PORT: ${PORT:-2203}
    ports:
      - "${PORT:-2203}:2203"

networks:
  default:
    external:
      name: jotace